### ISSUE TITLE
Make PHPThumb quality level editable by user

### ISSUE THREAD

**Issue by Aharito** [DivanDesign/MODXEvo.plugin.ManagerManager.mm_ddResizeImage#1]
The default PHPTHumb quality level **100** hard-coded in this plugin, so plugin produced **too large** optimised images in few cases (large-size original image, for example).

This quality level 100 set in assets\plugins\managermanager\widgets\ddresizeimage\ddresizeimage.php, line 83.

It would be very useful to **take out** this option in the user-defined plugin settings.

Below is a comparison of the size of compressed images, depending on the PHPThumb "quality" value (the original image is 3543 × 2362, 6.46 MB):
- Quality level 100 - 438 KB
- Quality level   95 - 241 KB (55%)
- Quality level   90 - 163 KB (37%)
- Quality level   85 - 127 KB (29%)

Experiment was performed on a real site, "quality"  level was edited directly in the plugin  code.

**Comment by Ronef** [comment]
:pray:
